language: node_js
node_js:
- "0.10"

before_script:
- npm install -g  balderdashy/sails appdevdesigns/appdev-cli#develop
- cd /tmp
- /home/travis/build/appdevdesigns/opstool-emailNotifications/test/setup/install.sh
- cd ad-test/node_modules
- mv /home/travis/build/appdevdesigns/opstool-emailNotifications .
- cd opstool-emailNotifications
- npm install mocha chai 
- npm install

script:
- npm test
 
